
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ 
/* do not edit */ 
/* do not edit */ import { User } from "./User";
/* do not edit */ 
/* do not edit */ 
/* do not edit */ export class TaskSolution {
/* do not edit */     
/* do not edit */     public id: string;
/* do not edit */ 
/* do not edit */     
/* do not edit */     public row: number;
/* do not edit */ 
/* do not edit */     
/* do not edit */     public col: string;
/* do not edit */ 
/* do not edit */     
/* do not edit */     public day: number;
/* do not edit */ 
/* do not edit */     
/* do not edit */     public user: User;
/* do not edit */ }
/* do not edit */