
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ 
/* do not edit */ 
/* do not edit */ import { TaskSolution } from "./TaskSolution";
/* do not edit */ 
/* do not edit */ 
/* do not edit */ 
/* do not edit */ export class User {
/* do not edit */     
/* do not edit */     public id: string;
/* do not edit */ 
/* do not edit */     
/* do not edit */     public nickname: string;
/* do not edit */ 
/* do not edit */     
/* do not edit */     public realname: string;
/* do not edit */ 
/* do not edit */     
/* do not edit */     public grade: string;
/* do not edit */ 
/* do not edit */     
/* do not edit */     public email: string;
/* do not edit */ 
/* do not edit */     
/* do not edit */     public isAdmin: boolean;
/* do not edit */ 
/* do not edit */     
/* do not edit */     public password: string;
/* do not edit */ 
/* do not edit */     
/* do not edit */     public passwordResetToken: string;
/* do not edit */ 
/* do not edit */     
/* do not edit */     
/* do not edit */     public createdAt: Date;
/* do not edit */ 
/* do not edit */     
/* do not edit */     
/* do not edit */     public updatedAt: Date;
/* do not edit */ 
/* do not edit */     
/* do not edit */     public solutions: TaskSolution[];
/* do not edit */ 
/* do not edit */     public jwtToken?: string;
/* do not edit */ 
/* do not edit */     public points?: number;
/* do not edit */ 
/* do not edit */     public place?: number;
/* do not edit */ 
/* do not edit */     public isYoung?: boolean;
/* do not edit */ 
/* do not edit */     
/* do not edit */ 
/* do not edit */     
/* do not edit */ }
/* do not edit */